// 東京主要駅マスターデータ（Phase 3基盤）
export const tokyoStations = [
  // 山手線主要駅
  {
    stationId: "shibuya",
    stationName: "渋谷",
    stationNameKana: "しぶや",
    stationNameEn: "Shibuya",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.658034,
    lng: 139.701636,
  },
  {
    stationId: "shinjuku",
    stationName: "新宿",
    stationNameKana: "しんじゅく",
    stationNameEn: "Shinjuku",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.689729,
    lng: 139.700464,
  },
  {
    stationId: "ikebukuro",
    stationName: "池袋",
    stationNameKana: "いけぶくろ",
    stationNameEn: "Ikebukuro",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.728926,
    lng: 139.71038,
  },
  {
    stationId: "tokyo",
    stationName: "東京",
    stationNameKana: "とうきょう",
    stationNameEn: "Tokyo",
    prefecture: "東京都",
    line: "JR中央線",
    lat: 35.681236,
    lng: 139.767125,
  },
  {
    stationId: "ueno",
    stationName: "上野",
    stationNameKana: "うえの",
    stationNameEn: "Ueno",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.713768,
    lng: 139.777254,
  },
  {
    stationId: "shinagawa",
    stationName: "品川",
    stationNameKana: "しながわ",
    stationNameEn: "Shinagawa",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.628471,
    lng: 139.73876,
  },
  {
    stationId: "akihabara",
    stationName: "秋葉原",
    stationNameKana: "あきはばら",
    stationNameEn: "Akihabara",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.698353,
    lng: 139.773114,
  },
  {
    stationId: "ebisu",
    stationName: "恵比寿",
    stationNameKana: "えびす",
    stationNameEn: "Ebisu",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.646685,
    lng: 139.710106,
  },
  {
    stationId: "meguro",
    stationName: "目黒",
    stationNameKana: "めぐろ",
    stationNameEn: "Meguro",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.633998,
    lng: 139.715828,
  },
  {
    stationId: "gotanda",
    stationName: "五反田",
    stationNameKana: "ごたんだ",
    stationNameEn: "Gotanda",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.625974,
    lng: 139.723822,
  },
  {
    stationId: "osaki",
    stationName: "大崎",
    stationNameKana: "おおさき",
    stationNameEn: "Osaki",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.619772,
    lng: 139.728439,
  },
  {
    stationId: "shimbashi",
    stationName: "新橋",
    stationNameKana: "しんばし",
    stationNameEn: "Shinbashi",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.666379,
    lng: 139.758304,
  },
  {
    stationId: "hamamatsucho",
    stationName: "浜松町",
    stationNameKana: "はままつちょう",
    stationNameEn: "Hamamatsucho",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.655391,
    lng: 139.756897,
  },
  {
    stationId: "tamachi",
    stationName: "田町",
    stationNameKana: "たまち",
    stationNameEn: "Tamachi",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.645736,
    lng: 139.747575,
  },
  {
    stationId: "yurakucho",
    stationName: "有楽町",
    stationNameKana: "ゆうらくちょう",
    stationNameEn: "Yurakucho",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.675069,
    lng: 139.763328,
  },
  {
    stationId: "kanda",
    stationName: "神田",
    stationNameKana: "かんだ",
    stationNameEn: "Kanda",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.691173,
    lng: 139.770641,
  },
  // メトロ主要駅
  {
    stationId: "ginza",
    stationName: "銀座",
    stationNameKana: "ぎんざ",
    stationNameEn: "Ginza",
    prefecture: "東京都",
    line: "東京メトロ銀座線",
    lat: 35.671989,
    lng: 139.763965,
  },
  {
    stationId: "roppongi",
    stationName: "六本木",
    stationNameKana: "ろっぽんぎ",
    stationNameEn: "Roppongi",
    prefecture: "東京都",
    line: "東京メトロ日比谷線",
    lat: 35.662836,
    lng: 139.731044,
  },
  {
    stationId: "nakameguro",
    stationName: "中目黒",
    stationNameKana: "なかめぐろ",
    stationNameEn: "Nakameguro",
    prefecture: "東京都",
    line: "東京メトロ日比谷線",
    lat: 35.644052,
    lng: 139.699356,
  },
  {
    stationId: "harajuku",
    stationName: "原宿",
    stationNameKana: "はらじゅく",
    stationNameEn: "Harajuku",
    prefecture: "東京都",
    line: "JR山手線",
    lat: 35.670168,
    lng: 139.702687,
  },
] as const;

export type Station = (typeof tokyoStations)[number];
export const stationIds = tokyoStations.map((s) => s.stationId);
